In [1]:
import numpy as np

#### numpy 切分/合并

##### 切分

In [5]:
# 水平切分
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

# 水平切分成2个数组
result = np.hsplit(arr, 2)
result
# [array([[1, 2],
#        [5, 6]]), 
#  array([[3, 4],
#        [7, 8]])]

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [6]:
# 垂直切分
arr = np.array([[1, 2], 
                [3, 4], 
                [5, 6]])

# 垂直切分成3个数组
result = np.vsplit(arr, 3)
result
# [array([[1, 2]]), 
#  array([[3, 4]]), 
#  array([[5, 6]])]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [ ]:
# 通用切分
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# 沿轴1切分(水平方向)
result = np.split(arr, 3, axis=1)
print(result)
# [array([[1],
#         [4],
#         [7]]), 
#  array([[2],
#         [5],
#         [8]]), 
#  array([[3],
#         [6],
#         [9]])]

# 沿轴0切分(垂直方向)
result = np.split(arr, 3, axis=0)
print(result)
# [array([[1, 2, 3]]), 
#  array([[4, 5, 6]]), 
#  array([[7, 8, 9]])]

##### 合并

In [11]:
# 水平合并
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)  # [1 2 3 4 5 6]

# 二维数组示例
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

result = np.hstack((a, b))
result
# [[1 4]
#  [2 5]
#  [3 6]]

[1 2 3 4 5 6]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
# 垂直合并
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
result
# [[1 2 3]
#  [4 5 6]]

# 二维数组示例
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

result = np.vstack((a, b))
result
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]
#  [6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# 通用合并
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 沿新轴0堆叠
result = np.stack((a, b), axis=0)
print(result)
# [[1 2 3]
#  [4 5 6]]

# 沿新轴1堆叠
result = np.stack((a, b), axis=1)
print(result)
# [[1 4]
#  [2 5]
#  [3 6]]

#### PAT-1039 到底买不买
1. 使用字典存储想要的珠子的颜色(key)和数量(value)
2. 使用元组对想要的珠子进行去重,用以简化对老板珠子的遍历
3. 遍历元组对老板的珠子进行遍历,检验是否有想要的珠
4. 如果有且数量够,则对下一个要买的珠子进行检验
5. 如果不够,则计算出缺多少,并用变量(lock)存储(因为不需要知道缺的是什么颜色)

In [ ]:
boos_beads = input()
target_beads = input()

target_dict = {}
for bead in target_beads:
    if bead in target_dict:
        target_dict[bead] += 1
    else:
        target_dict[bead] = 1

set_target = set(target_beads)

lock = 0
for i in set_target:
    if i in boos_beads:
        if boos_beads.count(i) >= target_dict[i]:
            continue
        else:
            lock += target_dict[i] - boos_beads.count(i)
    else:
        lock += target_dict[i]

if lock == 0:
    print("Yes", end=" ")
    print(len(boos_beads) - len(target_beads))
else:
    print("No", end=" ")
    print(lock)

Yes8


In [ ]:
# PAT --- 1039 ---到底买不买

given = list(input())  # 摊主的
want = list(input())   # 想要的
glen = len(given)
lst = []
for i in want:
    for j in given:
        if i == j:
            lst.append(i)
            given.remove(j)
            break

if len(lst) == len(want) :  # want表不为空，即还有想要的珠子没有取到
    print('Yes',glen-len(want))
else:  # wan
    print('No',len(want)-len(lst))

#ppRYYGrrYBR2258
#YrR8RrY



yes 8


In [1]:
# PAT --- 1039 ---到底买不买

given = list(input())  # 摊主的
want = list(input())   # 想要的
glen = len(given)
lst = []
for i in want:
    for j in given:
        if i == j:
            want.remove(i)
            given.remove(j)
            break

if len(lst) == len(want) :  # want表不为空，即还有想要的珠子没有取到
    print('Yes',glen-len(want))
else:  # wan
    print('No',len(want)-len(lst))

#ppRYYGrrYBR2258
#YrR8RrY



No 3


#### PAT-1047 团体编程赛

In [26]:
N = int(input())

team_score = {}

for i in range(N):
    t_m, score = input().split()
    team, member = t_m.split('-')
    if team not in team_score:
        team_score[team] = int(score)
    else:
        team_score[team] = team_score[team] + int(score)

win_team = max(team_score.items(), key=lambda x: x[1])

print(win_team[0],win_team[1])

3 88


#### PAT-1051 复数乘法
1. A + Bi = R(cos(P) + i sin(P))
2. A = R*cos(P)
3. B = R*sin(P)
4. (A1 + B1i) * (A2 + B2i) = (A1*A2 - B1 * B2) + (A1*B2 + B1*A2)i = R1*R2*(cos(P1 + P2) + sin(P1 + P2))i
5. 当负数很小时,格式化输出为-0.00,但实际应该按照0.00输出

```python

print(f'{-0.0000005:.2f}')
# 输出为 -0.00

```

In [ ]:
import math

R1, P1, R2, P2 = map(float, input().split())

A = R1 * R2 * math.cos(P1 + P2)
B = R1 * R2 * math.sin(P1 + P2)

if f'{A:.2f}' == '-0.00':
    A = 0.00
if f'{B:.2f}' == '-0.00':
    B = 0.00

if B < 0:
    print(f'{A:.2f}{B:.2f}i')
else:
    print(f'{A:.2f}+{B:.2f}i')


-8.68-8.23i


In [45]:
print(f'{-0.0000005:.2f}')

-0.00
