### 深度学习简介

1. 深度学习是一种基于神经网络的学习方法。
2. 深度学习需要更丰富的数据，更强大的计算资源。
3. 两大分支：
    - 计算机视觉
    - 自然语言处理

### 计算机视觉

#### 计算机视觉的定义
1. 对生物视觉的一种模拟。
2. 照相机 = 眼睛， 算法 = 大脑。
3. 实现图像理解是计算机视觉的终极目标。

#### 深度学习与传统机器学习的区别
1. 网络搭建
2. 没有特征工程

### 自然语言处理

### 强化学习：机器学习的一个范式

#### 强化学习四要素
1. 智能体：智能体是执行任务的客体，只能同过与环境互动来提升策略
2. 环境状态：
3. 行动
4. 反馈

#### 强化学习的目标
1. 强化学习的目标就是获得最多的累计奖励（正反馈）。
2. 幼童需要自己学习走路，不能有人指导，至于该如何学习走路。他需要通过不断尝试和外界对他的反馈来


### 深度学习框架

1. 框架存在的意义就是屏蔽底层细节，使研究者可以专注于模型结构。

#### caffe框架
1. 专精于图像处理。
2. 不需要编程能力。

#### TensorFlow

#### PyTorch

In [ ]:
# 查看 CUDA 版本和是否可用
import torch
print(torch.version.cuda)
print(torch.cuda.is_available())

11.8
True


In [ ]:
# 创建张量
import torch
print(torch.ones((2,20)))
print(torch.zeros((2,20)))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


### 简单的神经网络
1. 输入层
2. 隐藏层，激活函数激活后得到输出，输出可作为下一个隐藏层的输入
3. 输出层，接收隐藏层的输出，通过最后计算得到结果
    - **回归问题**：一般不加激活函数或用 ReLU / tanh
    - **二分类**：常用 sigmoid → 输出 (0,1) 概率。
    - **多分类**：常用 softmax → 输出概率分布。

In [ ]:
# 实现一个简单的神经网络
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

X = np.array([5,8]) # input 输入

# 第一层神经网络
w1 = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]]) # weights 权重
B1 = np.array([0.5,0.3,0.2]) # bias 偏置
A1 = np.dot(X, w1) + B1
Z1 = relu(A1)
print(Z1)

# 第二层神经网络
w2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]]) # weights 权重
B2 = np.array([0.4,0.6]) # bias 偏置
A2 = np.dot(Z1, w2) + B2
Z2 = relu(A2)
print(Z2)

# 第三层神经网络
w3 = np.array([[0.1,0.3],[0.2,0.4]]) # weights 权重
B3 = np.array([0.3,0.6]) # bias 偏置
A3 = np.dot(Z2, w3) + B3
Z3 = sigmoid(A3)
print(Z3)

[4.2 5.3 6.5]
[3.83 8.83]
[0.92048829 0.99493841]
